version: '3.9'

services:
  wordpress_db:
    image: mariadb:10.6
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: casbeghen_db
    secrets:
      - db_password
    networks:
      - app-network
    restart: always
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass $(cat /run/secrets/redis_password)
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
    secrets:
      - redis_password
    networks:
      - app-network
    restart: always
    volumes:
      - redis_data:/data

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    image: custom-wordpress:latest
    container_name: wordpress
    depends_on:
      - wordpress_db
      - redis
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: casbeghen_db
      WP_SITE_URL: http://casbeghen.com
      WP_TITLE: "My WordPress Site"
      WP_ADMIN_USER: deborah
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WP_ADMIN_EMAIL: deborahsbeghen@gmail.com
      WP_REDIS_HOST: redis
      WP_REDIS_PORT: 6379
      WP_REDIS_PASSWORD_FILE: /run/secrets/redis_password
    secrets:
      - db_password
      - redis_password
      - wp_admin_password
    networks:
      - app-network
    restart: always
    volumes:
      - wordpress_data:/var/www/html

  php_test:
    build:
      context: ./php-test
      dockerfile: Dockerfile
    image: php-test:latest
    container_name: php_test
    depends_on:
      - wordpress
    environment:
      PHP_TEST_MODE: true
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: casbeghen_db
    secrets:
      - db_password
    networks:
      - app-network
    restart: always
    ports:
      - "9001:9001"

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - wordpress
      - php_test
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - wordpress_data:/var/www/html
    networks:
      - app-network
    restart: always
    ports:
      - "80:80"

networks:
  app-network:
    driver: bridge

volumes:
  wordpress_data:
  db_data:
  redis_data:

secrets:
  db_password:
    file: ./secrets/db_password
  redis_password:
    file: ./secrets/redis_password
  wp_admin_password:
    file: ./secrets/wp_admin_password

